# Set the base image and working directory
FROM php:8.4-fpm-alpine
WORKDIR /var/www/html

# Install runtime dependencies
RUN apk add --no-cache icu-libs libzip curl git

# Install build dependencies, compile PHP extensions, and clean up
RUN apk add --no-cache --virtual .build-deps \
    autoconf \
    gcc \
    g++ \
    make \
    icu-dev \
    libzip-dev \
    oniguruma-dev \
    linux-headers \
    && docker-php-ext-install \
    intl \
    bcmath \
    pdo_mysql \
    zip \
    opcache \
    pcntl \
    && apk del .build-deps

# Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

COPY composer.json composer.lock ./
RUN composer install --no-interaction --prefer-dist --no-scripts

# Copy application code and set permissions

COPY --chown=www-data:www-data . .

RUN mkdir -p storage/framework/{sessions,views,cache} storage/logs bootstrap/cache \
    && chmod -R 775 storage bootstrap/cache

# Expose port and set the default command

EXPOSE 9000
CMD ["php-fpm"]